version: '2.2'

services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    environment:
      - "discovery.type=single-node"
    ports:
      - 9201:9200
      - 9300:9300

  proxy:
    image: nginx:1.17-alpine
    ports:
      - "8080:8080"
    volumes:
      - ./docker/vhost_feeding_performance.conf:/etc/nginx/conf.d/default.conf